### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Papadoubulus** [ProxmaDev/EAPIMySQLProvider#2]
Das Event "cn.nukkit.event.player.PlayerJoinEvent" konnte nicht zu "EconomyAPI v2.0.1": null in Zeile me.onebone.economyapi.EconomyAPI weitergegeben werden
01:12:31 [ERROR] Throwing
cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [nukkit.jar:?]
        at cn.nukkit.Player.doFirstSpawn(Player.java:878) [nukkit.jar:?]
        at cn.nukkit.Player.sendNextChunk(Player.java:839) [nukkit.jar:?]
        at cn.nukkit.Player.checkNetwork(Player.java:1855) [nukkit.jar:?]
        at cn.nukkit.Server.tick(Server.java:1146) [nukkit.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:911) [nukkit.jar:?]
        at cn.nukkit.Server.start(Server.java:888) [nukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:573) [nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]
Caused by: java.lang.NullPointerException
        at net.llamadevelopment.EAPIMySQLProvider.provider.MySQLProvider.accountExists(MySQLProvider.java:64) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.checkAndConvertLegacy(EconomyAPI.java:499) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.checkAndConvertLegacy(EconomyAPI.java:487) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.createAccount(EconomyAPI.java:102) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.createAccount(EconomyAPI.java:82) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.createAccount(EconomyAPI.java:78) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.createAccount(EconomyAPI.java:74) ~[?:?]
        at me.onebone.economyapi.EconomyAPI.onJoin(EconomyAPI.java:421) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit.jar:?]

**Comment by ProxmaDev** [comment]
Das spricht für einen Verbindungsverlust. Bitte prüfe die Daten die du in der config.yml angegeben hast. Möglicherweise sind sie falsch.

**Comment by Papadoubulus** [comment]
Ich habe alles richtig eingetragen welche version von der api hast du ?

**Comment by ProxmaDev** [comment]
Das Plugin haben wir mit der neuesten EconomyAPI Version getestet. Es funktioniert sowohl MySQL als auch MongoDB.

Bei dir ist das Problem, das es gar nichts zurückgibt. Evtl. existiert die Datenbank in MySQL nicht, das Passwort ist falsch oder etwas anderes. Das Plugin kann auch nichts anderes machen, als die Anfrage an den Server zu senden.

**Comment by Noreal2** [comment]
Hi wenn ich mich einmischen darf Bei mir funk das auch nicht

**Comment by ProxmaDev** [comment]
Das Problem wurde gefunden. Was ihr machen müsst, ist DbLib auf 1.0.1 oder höher updaten. Danach sollte es ohne Probleme funktionieren :)
